/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ContactInfoCreate,
  ContactInfoDeleteResponse,
  ContactInfoGetAllResponse,
  ContactInfoGetOneResponse,
  ContactInfoUpdate,
  GetApiV10ContactInfoParams
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a single contact info entry by its ID
 * @summary Get contact info by ID
 */
export const getApiV10ContactInfoId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ContactInfoGetOneResponse>(
      {url: `/api/v1.0/contactInfo/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10ContactInfoIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/contactInfo/${id}`
    ] as const;
    }

export const getGetApiV10ContactInfoIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/contactInfo/${id}`
    ] as const;
    }

    
export const getGetApiV10ContactInfoIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10ContactInfoId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10ContactInfoIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10ContactInfoId>>> = ({ signal }) => getApiV10ContactInfoId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10ContactInfoIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10ContactInfoId>>>
export type GetApiV10ContactInfoIdInfiniteQueryError = ErrorType<void>


export function useGetApiV10ContactInfoIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10ContactInfoId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10ContactInfoId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10ContactInfoId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10ContactInfoIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10ContactInfoId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10ContactInfoId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10ContactInfoId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10ContactInfoIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10ContactInfoId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get contact info by ID
 */

export function useGetApiV10ContactInfoIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10ContactInfoId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10ContactInfoIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get contact info by ID
 */
export const prefetchGetApiV10ContactInfoIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10ContactInfoIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10ContactInfoIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10ContactInfoIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10ContactInfoId>>> = ({ signal }) => getApiV10ContactInfoId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10ContactInfoIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10ContactInfoId>>>
export type GetApiV10ContactInfoIdQueryError = ErrorType<void>


export function useGetApiV10ContactInfoId<TData = Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10ContactInfoId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10ContactInfoId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10ContactInfoId<TData = Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10ContactInfoId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10ContactInfoId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10ContactInfoId<TData = Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get contact info by ID
 */

export function useGetApiV10ContactInfoId<TData = Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10ContactInfoIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get contact info by ID
 */
export const prefetchGetApiV10ContactInfoIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfoId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10ContactInfoIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update a single contact info entry by its ID
 * @summary Update contact info by ID
 */
export const putApiV10ContactInfoId = (
    id: string,
    contactInfoUpdate: BodyType<ContactInfoUpdate>,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<ContactInfoGetOneResponse>(
      {url: `/api/v1.0/contactInfo/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: contactInfoUpdate
    },
      options);
    }
  


export const getPutApiV10ContactInfoIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10ContactInfoId>>, TError,{id: string;data: BodyType<ContactInfoUpdate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10ContactInfoId>>, TError,{id: string;data: BodyType<ContactInfoUpdate>}, TContext> => {

const mutationKey = ['putApiV10ContactInfoId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10ContactInfoId>>, {id: string;data: BodyType<ContactInfoUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10ContactInfoId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10ContactInfoIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10ContactInfoId>>>
    export type PutApiV10ContactInfoIdMutationBody = BodyType<ContactInfoUpdate>
    export type PutApiV10ContactInfoIdMutationError = ErrorType<void>

    /**
 * @summary Update contact info by ID
 */
export const usePutApiV10ContactInfoId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10ContactInfoId>>, TError,{id: string;data: BodyType<ContactInfoUpdate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10ContactInfoId>>,
        TError,
        {id: string;data: BodyType<ContactInfoUpdate>},
        TContext
      > => {

      const mutationOptions = getPutApiV10ContactInfoIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single contact info entry by its ID
 * @summary Delete contact info by ID
 */
export const deleteApiV10ContactInfoId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<ContactInfoDeleteResponse>(
      {url: `/api/v1.0/contactInfo/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV10ContactInfoIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10ContactInfoId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10ContactInfoId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10ContactInfoId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10ContactInfoId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10ContactInfoId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10ContactInfoIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10ContactInfoId>>>
    
    export type DeleteApiV10ContactInfoIdMutationError = ErrorType<void>

    /**
 * @summary Delete contact info by ID
 */
export const useDeleteApiV10ContactInfoId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10ContactInfoId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10ContactInfoId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10ContactInfoIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve key/value contact info entries with pagination, filtering and sorting
 * @summary Get all contact infos
 */
export const getApiV10ContactInfo = (
    params?: GetApiV10ContactInfoParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ContactInfoGetAllResponse>(
      {url: `/api/v1.0/contactInfo`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10ContactInfoInfiniteQueryKey = (params?: GetApiV10ContactInfoParams,) => {
    return [
    'infinite', `/api/v1.0/contactInfo`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10ContactInfoQueryKey = (params?: GetApiV10ContactInfoParams,) => {
    return [
    `/api/v1.0/contactInfo`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10ContactInfoInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10ContactInfo>>>, TError = ErrorType<unknown>>(params?: GetApiV10ContactInfoParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10ContactInfoInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10ContactInfo>>> = ({ signal }) => getApiV10ContactInfo(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10ContactInfoInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10ContactInfo>>>
export type GetApiV10ContactInfoInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10ContactInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10ContactInfo>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10ContactInfoParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10ContactInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV10ContactInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10ContactInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10ContactInfo>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10ContactInfoParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10ContactInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV10ContactInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10ContactInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10ContactInfo>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10ContactInfoParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all contact infos
 */

export function useGetApiV10ContactInfoInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10ContactInfo>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10ContactInfoParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10ContactInfoInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all contact infos
 */
export const prefetchGetApiV10ContactInfoInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10ContactInfoParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10ContactInfoInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10ContactInfoQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError = ErrorType<unknown>>(params?: GetApiV10ContactInfoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10ContactInfoQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10ContactInfo>>> = ({ signal }) => getApiV10ContactInfo(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10ContactInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10ContactInfo>>>
export type GetApiV10ContactInfoQueryError = ErrorType<unknown>


export function useGetApiV10ContactInfo<TData = Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10ContactInfoParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10ContactInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV10ContactInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10ContactInfo<TData = Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError = ErrorType<unknown>>(
 params?: GetApiV10ContactInfoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10ContactInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiV10ContactInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10ContactInfo<TData = Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError = ErrorType<unknown>>(
 params?: GetApiV10ContactInfoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all contact infos
 */

export function useGetApiV10ContactInfo<TData = Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError = ErrorType<unknown>>(
 params?: GetApiV10ContactInfoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10ContactInfoQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all contact infos
 */
export const prefetchGetApiV10ContactInfoQuery = async <TData = Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10ContactInfoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10ContactInfo>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10ContactInfoQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new key/value contact info entry
 * @summary Create a contact info
 */
export const postApiV10ContactInfo = (
    contactInfoCreate: BodyType<ContactInfoCreate>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ContactInfoGetOneResponse>(
      {url: `/api/v1.0/contactInfo`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: contactInfoCreate, signal
    },
      options);
    }
  


export const getPostApiV10ContactInfoMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10ContactInfo>>, TError,{data: BodyType<ContactInfoCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10ContactInfo>>, TError,{data: BodyType<ContactInfoCreate>}, TContext> => {

const mutationKey = ['postApiV10ContactInfo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10ContactInfo>>, {data: BodyType<ContactInfoCreate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10ContactInfo(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10ContactInfoMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10ContactInfo>>>
    export type PostApiV10ContactInfoMutationBody = BodyType<ContactInfoCreate>
    export type PostApiV10ContactInfoMutationError = ErrorType<void>

    /**
 * @summary Create a contact info
 */
export const usePostApiV10ContactInfo = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10ContactInfo>>, TError,{data: BodyType<ContactInfoCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10ContactInfo>>,
        TError,
        {data: BodyType<ContactInfoCreate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10ContactInfoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    