/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV10HeaderConfigId200,
  GetApiV10HeaderConfigId200,
  GetApiV10HeaderConfigParams,
  HeaderConfigMutate,
  PostApiV10HeaderConfig200,
  PutApiV10HeaderConfigId200,
  ResponseGetAllData
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a single headerConfig record by its ID
 * @summary Get headerConfig by ID
 */
export const getApiV10HeaderConfigId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<GetApiV10HeaderConfigId200>(
      {url: `/api/v1.0/headerConfig/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10HeaderConfigIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/headerConfig/${id}`
    ] as const;
    }

export const getGetApiV10HeaderConfigIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/headerConfig/${id}`
    ] as const;
    }

    
export const getGetApiV10HeaderConfigIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10HeaderConfigIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>> = ({ signal }) => getApiV10HeaderConfigId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10HeaderConfigIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>>
export type GetApiV10HeaderConfigIdInfiniteQueryError = ErrorType<void>


export function useGetApiV10HeaderConfigIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10HeaderConfigId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10HeaderConfigId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10HeaderConfigIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10HeaderConfigId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10HeaderConfigId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10HeaderConfigIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get headerConfig by ID
 */

export function useGetApiV10HeaderConfigIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10HeaderConfigIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get headerConfig by ID
 */
export const prefetchGetApiV10HeaderConfigIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10HeaderConfigIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10HeaderConfigIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10HeaderConfigIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>> = ({ signal }) => getApiV10HeaderConfigId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10HeaderConfigIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>>
export type GetApiV10HeaderConfigIdQueryError = ErrorType<void>


export function useGetApiV10HeaderConfigId<TData = Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10HeaderConfigId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10HeaderConfigId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10HeaderConfigId<TData = Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10HeaderConfigId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10HeaderConfigId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10HeaderConfigId<TData = Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get headerConfig by ID
 */

export function useGetApiV10HeaderConfigId<TData = Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10HeaderConfigIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get headerConfig by ID
 */
export const prefetchGetApiV10HeaderConfigIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfigId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10HeaderConfigIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update a single headerConfig record by its ID
 * @summary Update headerConfig by ID
 */
export const putApiV10HeaderConfigId = (
    id: string,
    headerConfigMutate: BodyType<HeaderConfigMutate>,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<PutApiV10HeaderConfigId200>(
      {url: `/api/v1.0/headerConfig/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: headerConfigMutate
    },
      options);
    }
  


export const getPutApiV10HeaderConfigIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10HeaderConfigId>>, TError,{id: string;data: BodyType<HeaderConfigMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10HeaderConfigId>>, TError,{id: string;data: BodyType<HeaderConfigMutate>}, TContext> => {

const mutationKey = ['putApiV10HeaderConfigId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10HeaderConfigId>>, {id: string;data: BodyType<HeaderConfigMutate>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10HeaderConfigId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10HeaderConfigIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10HeaderConfigId>>>
    export type PutApiV10HeaderConfigIdMutationBody = BodyType<HeaderConfigMutate>
    export type PutApiV10HeaderConfigIdMutationError = ErrorType<void>

    /**
 * @summary Update headerConfig by ID
 */
export const usePutApiV10HeaderConfigId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10HeaderConfigId>>, TError,{id: string;data: BodyType<HeaderConfigMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10HeaderConfigId>>,
        TError,
        {id: string;data: BodyType<HeaderConfigMutate>},
        TContext
      > => {

      const mutationOptions = getPutApiV10HeaderConfigIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single headerConfig record by its ID
 * @summary Delete headerConfig by ID
 */
export const deleteApiV10HeaderConfigId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<DeleteApiV10HeaderConfigId200>(
      {url: `/api/v1.0/headerConfig/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV10HeaderConfigIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10HeaderConfigId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10HeaderConfigId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10HeaderConfigId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10HeaderConfigId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10HeaderConfigId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10HeaderConfigIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10HeaderConfigId>>>
    
    export type DeleteApiV10HeaderConfigIdMutationError = ErrorType<void>

    /**
 * @summary Delete headerConfig by ID
 */
export const useDeleteApiV10HeaderConfigId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10HeaderConfigId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10HeaderConfigId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10HeaderConfigIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of headerConfig with pagination, filtering and sorting
 * @summary Get all headerConfig
 */
export const getApiV10HeaderConfig = (
    params?: GetApiV10HeaderConfigParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ResponseGetAllData>(
      {url: `/api/v1.0/headerConfig`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10HeaderConfigInfiniteQueryKey = (params?: GetApiV10HeaderConfigParams,) => {
    return [
    'infinite', `/api/v1.0/headerConfig`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10HeaderConfigQueryKey = (params?: GetApiV10HeaderConfigParams,) => {
    return [
    `/api/v1.0/headerConfig`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10HeaderConfigInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10HeaderConfig>>>, TError = ErrorType<unknown>>(params?: GetApiV10HeaderConfigParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10HeaderConfigInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10HeaderConfig>>> = ({ signal }) => getApiV10HeaderConfig(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10HeaderConfigInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10HeaderConfig>>>
export type GetApiV10HeaderConfigInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10HeaderConfigInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10HeaderConfig>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10HeaderConfigParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10HeaderConfig>>,
          TError,
          Awaited<ReturnType<typeof getApiV10HeaderConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10HeaderConfigInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10HeaderConfig>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10HeaderConfigParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10HeaderConfig>>,
          TError,
          Awaited<ReturnType<typeof getApiV10HeaderConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10HeaderConfigInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10HeaderConfig>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10HeaderConfigParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all headerConfig
 */

export function useGetApiV10HeaderConfigInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10HeaderConfig>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10HeaderConfigParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10HeaderConfigInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all headerConfig
 */
export const prefetchGetApiV10HeaderConfigInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10HeaderConfigParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10HeaderConfigInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10HeaderConfigQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError = ErrorType<unknown>>(params?: GetApiV10HeaderConfigParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10HeaderConfigQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10HeaderConfig>>> = ({ signal }) => getApiV10HeaderConfig(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10HeaderConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10HeaderConfig>>>
export type GetApiV10HeaderConfigQueryError = ErrorType<unknown>


export function useGetApiV10HeaderConfig<TData = Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10HeaderConfigParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10HeaderConfig>>,
          TError,
          Awaited<ReturnType<typeof getApiV10HeaderConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10HeaderConfig<TData = Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError = ErrorType<unknown>>(
 params?: GetApiV10HeaderConfigParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10HeaderConfig>>,
          TError,
          Awaited<ReturnType<typeof getApiV10HeaderConfig>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10HeaderConfig<TData = Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError = ErrorType<unknown>>(
 params?: GetApiV10HeaderConfigParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all headerConfig
 */

export function useGetApiV10HeaderConfig<TData = Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError = ErrorType<unknown>>(
 params?: GetApiV10HeaderConfigParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10HeaderConfigQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all headerConfig
 */
export const prefetchGetApiV10HeaderConfigQuery = async <TData = Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10HeaderConfigParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10HeaderConfig>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10HeaderConfigQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new headerConfig record
 * @summary Create a headerConfig
 */
export const postApiV10HeaderConfig = (
    headerConfigMutate: BodyType<HeaderConfigMutate>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PostApiV10HeaderConfig200>(
      {url: `/api/v1.0/headerConfig`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: headerConfigMutate, signal
    },
      options);
    }
  


export const getPostApiV10HeaderConfigMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10HeaderConfig>>, TError,{data: BodyType<HeaderConfigMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10HeaderConfig>>, TError,{data: BodyType<HeaderConfigMutate>}, TContext> => {

const mutationKey = ['postApiV10HeaderConfig'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10HeaderConfig>>, {data: BodyType<HeaderConfigMutate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10HeaderConfig(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10HeaderConfigMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10HeaderConfig>>>
    export type PostApiV10HeaderConfigMutationBody = BodyType<HeaderConfigMutate>
    export type PostApiV10HeaderConfigMutationError = ErrorType<unknown>

    /**
 * @summary Create a headerConfig
 */
export const usePostApiV10HeaderConfig = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10HeaderConfig>>, TError,{data: BodyType<HeaderConfigMutate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10HeaderConfig>>,
        TError,
        {data: BodyType<HeaderConfigMutate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10HeaderConfigMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    