/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiV10JobParams,
  JobCreate,
  JobDeleteResponse,
  JobGetAllResponse,
  JobGetOneResponse,
  JobUpdate
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a single recruitment posting by its ID
 * @summary Get job by ID
 */
export const getApiV10JobId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<JobGetOneResponse>(
      {url: `/api/v1.0/job/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10JobIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/job/${id}`
    ] as const;
    }

export const getGetApiV10JobIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/job/${id}`
    ] as const;
    }

    
export const getGetApiV10JobIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10JobId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10JobId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10JobIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10JobId>>> = ({ signal }) => getApiV10JobId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10JobId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10JobIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10JobId>>>
export type GetApiV10JobIdInfiniteQueryError = ErrorType<void>


export function useGetApiV10JobIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10JobId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10JobId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10JobId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10JobId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10JobIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10JobId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10JobId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10JobId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10JobId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10JobIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10JobId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10JobId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get job by ID
 */

export function useGetApiV10JobIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10JobId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10JobId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10JobIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get job by ID
 */
export const prefetchGetApiV10JobIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10JobId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10JobId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10JobIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10JobIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10JobId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10JobId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10JobIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10JobId>>> = ({ signal }) => getApiV10JobId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10JobId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10JobIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10JobId>>>
export type GetApiV10JobIdQueryError = ErrorType<void>


export function useGetApiV10JobId<TData = Awaited<ReturnType<typeof getApiV10JobId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10JobId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10JobId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10JobId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10JobId<TData = Awaited<ReturnType<typeof getApiV10JobId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10JobId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10JobId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10JobId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10JobId<TData = Awaited<ReturnType<typeof getApiV10JobId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10JobId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get job by ID
 */

export function useGetApiV10JobId<TData = Awaited<ReturnType<typeof getApiV10JobId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10JobId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10JobIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get job by ID
 */
export const prefetchGetApiV10JobIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10JobId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10JobId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10JobIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update a single recruitment posting by its ID
 * @summary Update job by ID
 */
export const putApiV10JobId = (
    id: string,
    jobUpdate: BodyType<JobUpdate>,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<JobGetOneResponse>(
      {url: `/api/v1.0/job/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: jobUpdate
    },
      options);
    }
  


export const getPutApiV10JobIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10JobId>>, TError,{id: string;data: BodyType<JobUpdate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10JobId>>, TError,{id: string;data: BodyType<JobUpdate>}, TContext> => {

const mutationKey = ['putApiV10JobId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10JobId>>, {id: string;data: BodyType<JobUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10JobId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10JobIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10JobId>>>
    export type PutApiV10JobIdMutationBody = BodyType<JobUpdate>
    export type PutApiV10JobIdMutationError = ErrorType<void>

    /**
 * @summary Update job by ID
 */
export const usePutApiV10JobId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10JobId>>, TError,{id: string;data: BodyType<JobUpdate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10JobId>>,
        TError,
        {id: string;data: BodyType<JobUpdate>},
        TContext
      > => {

      const mutationOptions = getPutApiV10JobIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single recruitment posting by its ID
 * @summary Delete job by ID
 */
export const deleteApiV10JobId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<JobDeleteResponse>(
      {url: `/api/v1.0/job/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV10JobIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10JobId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10JobId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10JobId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10JobId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10JobId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10JobIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10JobId>>>
    
    export type DeleteApiV10JobIdMutationError = ErrorType<void>

    /**
 * @summary Delete job by ID
 */
export const useDeleteApiV10JobId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10JobId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10JobId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10JobIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of recruitment postings with pagination, filtering and sorting
 * @summary Get all jobs
 */
export const getApiV10Job = (
    params?: GetApiV10JobParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<JobGetAllResponse>(
      {url: `/api/v1.0/job`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10JobInfiniteQueryKey = (params?: GetApiV10JobParams,) => {
    return [
    'infinite', `/api/v1.0/job`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10JobQueryKey = (params?: GetApiV10JobParams,) => {
    return [
    `/api/v1.0/job`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10JobInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Job>>>, TError = ErrorType<unknown>>(params?: GetApiV10JobParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Job>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10JobInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Job>>> = ({ signal }) => getApiV10Job(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Job>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10JobInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Job>>>
export type GetApiV10JobInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10JobInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Job>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10JobParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Job>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Job>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Job>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10JobInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Job>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10JobParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Job>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Job>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Job>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10JobInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Job>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10JobParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Job>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all jobs
 */

export function useGetApiV10JobInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Job>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10JobParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Job>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10JobInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all jobs
 */
export const prefetchGetApiV10JobInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10Job>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10JobParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Job>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10JobInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10JobQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10Job>>, TError = ErrorType<unknown>>(params?: GetApiV10JobParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Job>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10JobQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Job>>> = ({ signal }) => getApiV10Job(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10Job>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10JobQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Job>>>
export type GetApiV10JobQueryError = ErrorType<unknown>


export function useGetApiV10Job<TData = Awaited<ReturnType<typeof getApiV10Job>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10JobParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Job>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Job>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Job>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Job<TData = Awaited<ReturnType<typeof getApiV10Job>>, TError = ErrorType<unknown>>(
 params?: GetApiV10JobParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Job>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Job>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Job>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Job<TData = Awaited<ReturnType<typeof getApiV10Job>>, TError = ErrorType<unknown>>(
 params?: GetApiV10JobParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Job>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all jobs
 */

export function useGetApiV10Job<TData = Awaited<ReturnType<typeof getApiV10Job>>, TError = ErrorType<unknown>>(
 params?: GetApiV10JobParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Job>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10JobQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all jobs
 */
export const prefetchGetApiV10JobQuery = async <TData = Awaited<ReturnType<typeof getApiV10Job>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10JobParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Job>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10JobQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new recruitment posting
 * @summary Create a job
 */
export const postApiV10Job = (
    jobCreate: BodyType<JobCreate>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<JobGetOneResponse>(
      {url: `/api/v1.0/job`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: jobCreate, signal
    },
      options);
    }
  


export const getPostApiV10JobMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Job>>, TError,{data: BodyType<JobCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10Job>>, TError,{data: BodyType<JobCreate>}, TContext> => {

const mutationKey = ['postApiV10Job'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10Job>>, {data: BodyType<JobCreate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10Job(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10JobMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10Job>>>
    export type PostApiV10JobMutationBody = BodyType<JobCreate>
    export type PostApiV10JobMutationError = ErrorType<void>

    /**
 * @summary Create a job
 */
export const usePostApiV10Job = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Job>>, TError,{data: BodyType<JobCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10Job>>,
        TError,
        {data: BodyType<JobCreate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10JobMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    