/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiV10LeaderParams,
  LeaderCreate,
  LeaderDeleteResponse,
  LeaderGetAllResponse,
  LeaderGetOneResponse,
  LeaderUpdate
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a single company leader by its ID
 * @summary Get leader by ID
 */
export const getApiV10LeaderId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<LeaderGetOneResponse>(
      {url: `/api/v1.0/leader/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10LeaderIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/leader/${id}`
    ] as const;
    }

export const getGetApiV10LeaderIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/leader/${id}`
    ] as const;
    }

    
export const getGetApiV10LeaderIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10LeaderId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LeaderId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10LeaderIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10LeaderId>>> = ({ signal }) => getApiV10LeaderId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LeaderId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10LeaderIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10LeaderId>>>
export type GetApiV10LeaderIdInfiniteQueryError = ErrorType<void>


export function useGetApiV10LeaderIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10LeaderId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LeaderId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10LeaderId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10LeaderId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LeaderIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10LeaderId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LeaderId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10LeaderId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10LeaderId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LeaderIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10LeaderId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LeaderId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get leader by ID
 */

export function useGetApiV10LeaderIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10LeaderId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LeaderId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10LeaderIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get leader by ID
 */
export const prefetchGetApiV10LeaderIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10LeaderId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10LeaderId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10LeaderIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10LeaderIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10LeaderId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LeaderId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10LeaderIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10LeaderId>>> = ({ signal }) => getApiV10LeaderId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10LeaderId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10LeaderIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10LeaderId>>>
export type GetApiV10LeaderIdQueryError = ErrorType<void>


export function useGetApiV10LeaderId<TData = Awaited<ReturnType<typeof getApiV10LeaderId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LeaderId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10LeaderId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10LeaderId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LeaderId<TData = Awaited<ReturnType<typeof getApiV10LeaderId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LeaderId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10LeaderId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10LeaderId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LeaderId<TData = Awaited<ReturnType<typeof getApiV10LeaderId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LeaderId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get leader by ID
 */

export function useGetApiV10LeaderId<TData = Awaited<ReturnType<typeof getApiV10LeaderId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LeaderId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10LeaderIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get leader by ID
 */
export const prefetchGetApiV10LeaderIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10LeaderId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10LeaderId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10LeaderIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update a single company leader by its ID
 * @summary Update leader by ID
 */
export const putApiV10LeaderId = (
    id: string,
    leaderUpdate: BodyType<LeaderUpdate>,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<LeaderGetOneResponse>(
      {url: `/api/v1.0/leader/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: leaderUpdate
    },
      options);
    }
  


export const getPutApiV10LeaderIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10LeaderId>>, TError,{id: string;data: BodyType<LeaderUpdate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10LeaderId>>, TError,{id: string;data: BodyType<LeaderUpdate>}, TContext> => {

const mutationKey = ['putApiV10LeaderId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10LeaderId>>, {id: string;data: BodyType<LeaderUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10LeaderId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10LeaderIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10LeaderId>>>
    export type PutApiV10LeaderIdMutationBody = BodyType<LeaderUpdate>
    export type PutApiV10LeaderIdMutationError = ErrorType<void>

    /**
 * @summary Update leader by ID
 */
export const usePutApiV10LeaderId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10LeaderId>>, TError,{id: string;data: BodyType<LeaderUpdate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10LeaderId>>,
        TError,
        {id: string;data: BodyType<LeaderUpdate>},
        TContext
      > => {

      const mutationOptions = getPutApiV10LeaderIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single company leader by its ID
 * @summary Delete leader by ID
 */
export const deleteApiV10LeaderId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<LeaderDeleteResponse>(
      {url: `/api/v1.0/leader/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV10LeaderIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10LeaderId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10LeaderId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10LeaderId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10LeaderId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10LeaderId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10LeaderIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10LeaderId>>>
    
    export type DeleteApiV10LeaderIdMutationError = ErrorType<void>

    /**
 * @summary Delete leader by ID
 */
export const useDeleteApiV10LeaderId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10LeaderId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10LeaderId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10LeaderIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of company leaders with pagination, filtering and sorting
 * @summary Get all leaders
 */
export const getApiV10Leader = (
    params?: GetApiV10LeaderParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<LeaderGetAllResponse>(
      {url: `/api/v1.0/leader`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10LeaderInfiniteQueryKey = (params?: GetApiV10LeaderParams,) => {
    return [
    'infinite', `/api/v1.0/leader`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10LeaderQueryKey = (params?: GetApiV10LeaderParams,) => {
    return [
    `/api/v1.0/leader`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10LeaderInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Leader>>>, TError = ErrorType<unknown>>(params?: GetApiV10LeaderParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Leader>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10LeaderInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Leader>>> = ({ signal }) => getApiV10Leader(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Leader>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10LeaderInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Leader>>>
export type GetApiV10LeaderInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10LeaderInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Leader>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10LeaderParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Leader>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Leader>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Leader>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LeaderInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Leader>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LeaderParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Leader>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Leader>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Leader>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10LeaderInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Leader>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LeaderParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Leader>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all leaders
 */

export function useGetApiV10LeaderInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Leader>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LeaderParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Leader>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10LeaderInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all leaders
 */
export const prefetchGetApiV10LeaderInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10Leader>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10LeaderParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Leader>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10LeaderInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10LeaderQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10Leader>>, TError = ErrorType<unknown>>(params?: GetApiV10LeaderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Leader>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10LeaderQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Leader>>> = ({ signal }) => getApiV10Leader(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10Leader>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10LeaderQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Leader>>>
export type GetApiV10LeaderQueryError = ErrorType<unknown>


export function useGetApiV10Leader<TData = Awaited<ReturnType<typeof getApiV10Leader>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10LeaderParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Leader>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Leader>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Leader>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Leader<TData = Awaited<ReturnType<typeof getApiV10Leader>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LeaderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Leader>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Leader>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Leader>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Leader<TData = Awaited<ReturnType<typeof getApiV10Leader>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LeaderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Leader>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all leaders
 */

export function useGetApiV10Leader<TData = Awaited<ReturnType<typeof getApiV10Leader>>, TError = ErrorType<unknown>>(
 params?: GetApiV10LeaderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Leader>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10LeaderQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all leaders
 */
export const prefetchGetApiV10LeaderQuery = async <TData = Awaited<ReturnType<typeof getApiV10Leader>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10LeaderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Leader>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10LeaderQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new company leader
 * @summary Create a leader
 */
export const postApiV10Leader = (
    leaderCreate: BodyType<LeaderCreate>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<LeaderGetOneResponse>(
      {url: `/api/v1.0/leader`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: leaderCreate, signal
    },
      options);
    }
  


export const getPostApiV10LeaderMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Leader>>, TError,{data: BodyType<LeaderCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10Leader>>, TError,{data: BodyType<LeaderCreate>}, TContext> => {

const mutationKey = ['postApiV10Leader'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10Leader>>, {data: BodyType<LeaderCreate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10Leader(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10LeaderMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10Leader>>>
    export type PostApiV10LeaderMutationBody = BodyType<LeaderCreate>
    export type PostApiV10LeaderMutationError = ErrorType<void>

    /**
 * @summary Create a leader
 */
export const usePostApiV10Leader = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Leader>>, TError,{data: BodyType<LeaderCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10Leader>>,
        TError,
        {data: BodyType<LeaderCreate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10LeaderMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    