/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiV10PartnerParams,
  PartnerCreate,
  PartnerDeleteResponse,
  PartnerGetAllResponse,
  PartnerGetOneResponse,
  PartnerUpdate
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a single partner record by its ID
 * @summary Get partner by ID
 */
export const getApiV10PartnerId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PartnerGetOneResponse>(
      {url: `/api/v1.0/partner/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10PartnerIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/partner/${id}`
    ] as const;
    }

export const getGetApiV10PartnerIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/partner/${id}`
    ] as const;
    }

    
export const getGetApiV10PartnerIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PartnerId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PartnerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PartnerIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10PartnerId>>> = ({ signal }) => getApiV10PartnerId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PartnerId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PartnerIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10PartnerId>>>
export type GetApiV10PartnerIdInfiniteQueryError = ErrorType<void>


export function useGetApiV10PartnerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PartnerId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PartnerId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PartnerId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PartnerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PartnerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PartnerId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PartnerId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PartnerId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PartnerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PartnerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PartnerId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PartnerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get partner by ID
 */

export function useGetApiV10PartnerIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10PartnerId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PartnerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PartnerIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get partner by ID
 */
export const prefetchGetApiV10PartnerIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10PartnerId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10PartnerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10PartnerIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10PartnerIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10PartnerId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PartnerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PartnerIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10PartnerId>>> = ({ signal }) => getApiV10PartnerId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10PartnerId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PartnerIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10PartnerId>>>
export type GetApiV10PartnerIdQueryError = ErrorType<void>


export function useGetApiV10PartnerId<TData = Awaited<ReturnType<typeof getApiV10PartnerId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PartnerId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PartnerId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PartnerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PartnerId<TData = Awaited<ReturnType<typeof getApiV10PartnerId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PartnerId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10PartnerId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10PartnerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PartnerId<TData = Awaited<ReturnType<typeof getApiV10PartnerId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PartnerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get partner by ID
 */

export function useGetApiV10PartnerId<TData = Awaited<ReturnType<typeof getApiV10PartnerId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PartnerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PartnerIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get partner by ID
 */
export const prefetchGetApiV10PartnerIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10PartnerId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10PartnerId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10PartnerIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update a single partner record by its ID
 * @summary Update partner by ID
 */
export const putApiV10PartnerId = (
    id: string,
    partnerUpdate: BodyType<PartnerUpdate>,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<PartnerGetOneResponse>(
      {url: `/api/v1.0/partner/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: partnerUpdate
    },
      options);
    }
  


export const getPutApiV10PartnerIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10PartnerId>>, TError,{id: string;data: BodyType<PartnerUpdate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10PartnerId>>, TError,{id: string;data: BodyType<PartnerUpdate>}, TContext> => {

const mutationKey = ['putApiV10PartnerId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10PartnerId>>, {id: string;data: BodyType<PartnerUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10PartnerId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10PartnerIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10PartnerId>>>
    export type PutApiV10PartnerIdMutationBody = BodyType<PartnerUpdate>
    export type PutApiV10PartnerIdMutationError = ErrorType<void>

    /**
 * @summary Update partner by ID
 */
export const usePutApiV10PartnerId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10PartnerId>>, TError,{id: string;data: BodyType<PartnerUpdate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10PartnerId>>,
        TError,
        {id: string;data: BodyType<PartnerUpdate>},
        TContext
      > => {

      const mutationOptions = getPutApiV10PartnerIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single partner record by its ID
 * @summary Delete partner by ID
 */
export const deleteApiV10PartnerId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<PartnerDeleteResponse>(
      {url: `/api/v1.0/partner/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV10PartnerIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10PartnerId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10PartnerId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10PartnerId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10PartnerId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10PartnerId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10PartnerIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10PartnerId>>>
    
    export type DeleteApiV10PartnerIdMutationError = ErrorType<void>

    /**
 * @summary Delete partner by ID
 */
export const useDeleteApiV10PartnerId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10PartnerId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10PartnerId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10PartnerIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of partner with pagination, filtering and sorting
 * @summary Get all partner
 */
export const getApiV10Partner = (
    params?: GetApiV10PartnerParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PartnerGetAllResponse>(
      {url: `/api/v1.0/partner`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10PartnerInfiniteQueryKey = (params?: GetApiV10PartnerParams,) => {
    return [
    'infinite', `/api/v1.0/partner`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10PartnerQueryKey = (params?: GetApiV10PartnerParams,) => {
    return [
    `/api/v1.0/partner`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10PartnerInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Partner>>>, TError = ErrorType<unknown>>(params?: GetApiV10PartnerParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Partner>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PartnerInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Partner>>> = ({ signal }) => getApiV10Partner(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Partner>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PartnerInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Partner>>>
export type GetApiV10PartnerInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10PartnerInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Partner>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10PartnerParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Partner>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Partner>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Partner>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PartnerInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Partner>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PartnerParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Partner>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Partner>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Partner>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10PartnerInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Partner>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PartnerParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Partner>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all partner
 */

export function useGetApiV10PartnerInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Partner>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PartnerParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Partner>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PartnerInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all partner
 */
export const prefetchGetApiV10PartnerInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10Partner>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10PartnerParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Partner>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10PartnerInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10PartnerQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10Partner>>, TError = ErrorType<unknown>>(params?: GetApiV10PartnerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Partner>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10PartnerQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Partner>>> = ({ signal }) => getApiV10Partner(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10Partner>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10PartnerQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Partner>>>
export type GetApiV10PartnerQueryError = ErrorType<unknown>


export function useGetApiV10Partner<TData = Awaited<ReturnType<typeof getApiV10Partner>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10PartnerParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Partner>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Partner>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Partner>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Partner<TData = Awaited<ReturnType<typeof getApiV10Partner>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PartnerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Partner>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Partner>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Partner>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Partner<TData = Awaited<ReturnType<typeof getApiV10Partner>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PartnerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Partner>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all partner
 */

export function useGetApiV10Partner<TData = Awaited<ReturnType<typeof getApiV10Partner>>, TError = ErrorType<unknown>>(
 params?: GetApiV10PartnerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Partner>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10PartnerQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all partner
 */
export const prefetchGetApiV10PartnerQuery = async <TData = Awaited<ReturnType<typeof getApiV10Partner>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10PartnerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Partner>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10PartnerQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new partner record
 * @summary Create a partner
 */
export const postApiV10Partner = (
    partnerCreate: BodyType<PartnerCreate>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<PartnerGetOneResponse>(
      {url: `/api/v1.0/partner`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: partnerCreate, signal
    },
      options);
    }
  


export const getPostApiV10PartnerMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Partner>>, TError,{data: BodyType<PartnerCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10Partner>>, TError,{data: BodyType<PartnerCreate>}, TContext> => {

const mutationKey = ['postApiV10Partner'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10Partner>>, {data: BodyType<PartnerCreate>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10Partner(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10PartnerMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10Partner>>>
    export type PostApiV10PartnerMutationBody = BodyType<PartnerCreate>
    export type PostApiV10PartnerMutationError = ErrorType<void>

    /**
 * @summary Create a partner
 */
export const usePostApiV10Partner = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Partner>>, TError,{data: BodyType<PartnerCreate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10Partner>>,
        TError,
        {data: BodyType<PartnerCreate>},
        TContext
      > => {

      const mutationOptions = getPostApiV10PartnerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    