/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiV10RoleIdPermission200,
  GetApiV10RoleParams,
  PostApiV10RoleBody,
  PutApiV10RoleIdPermissionBody,
  ResponseGetAllData,
  RoleUpdate
} from '../models';

import { useCustomClient } from '../mutator/custom-client';
import type { ErrorType , BodyType } from '../mutator/custom-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a single role by its ID, including users assigned to this role
 * @summary Get role by ID
 */
export const getApiV10RoleId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<void>(
      {url: `/api/v1.0/role/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10RoleIdInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/role/${id}`
    ] as const;
    }

export const getGetApiV10RoleIdQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/role/${id}`
    ] as const;
    }

    
export const getGetApiV10RoleIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10RoleId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RoleId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10RoleIdInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10RoleId>>> = ({ signal }) => getApiV10RoleId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RoleId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10RoleIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10RoleId>>>
export type GetApiV10RoleIdInfiniteQueryError = ErrorType<void>


export function useGetApiV10RoleIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10RoleId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RoleId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10RoleId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10RoleId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10RoleIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10RoleId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RoleId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10RoleId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10RoleId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10RoleIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10RoleId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RoleId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get role by ID
 */

export function useGetApiV10RoleIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10RoleId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RoleId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10RoleIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get role by ID
 */
export const prefetchGetApiV10RoleIdInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10RoleId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RoleId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10RoleIdInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10RoleIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10RoleId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RoleId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10RoleIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10RoleId>>> = ({ signal }) => getApiV10RoleId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10RoleId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10RoleIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10RoleId>>>
export type GetApiV10RoleIdQueryError = ErrorType<void>


export function useGetApiV10RoleId<TData = Awaited<ReturnType<typeof getApiV10RoleId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RoleId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10RoleId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10RoleId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10RoleId<TData = Awaited<ReturnType<typeof getApiV10RoleId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RoleId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10RoleId>>,
          TError,
          Awaited<ReturnType<typeof getApiV10RoleId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10RoleId<TData = Awaited<ReturnType<typeof getApiV10RoleId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RoleId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get role by ID
 */

export function useGetApiV10RoleId<TData = Awaited<ReturnType<typeof getApiV10RoleId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RoleId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10RoleIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get role by ID
 */
export const prefetchGetApiV10RoleIdQuery = async <TData = Awaited<ReturnType<typeof getApiV10RoleId>>, TError = ErrorType<void>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RoleId>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10RoleIdQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Update a single role record by its ID
 * @summary Update role by ID
 */
export const putApiV10RoleId = (
    id: string,
    roleUpdate: BodyType<RoleUpdate>,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<void>(
      {url: `/api/v1.0/role/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: roleUpdate
    },
      options);
    }
  


export const getPutApiV10RoleIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10RoleId>>, TError,{id: string;data: BodyType<RoleUpdate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10RoleId>>, TError,{id: string;data: BodyType<RoleUpdate>}, TContext> => {

const mutationKey = ['putApiV10RoleId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10RoleId>>, {id: string;data: BodyType<RoleUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10RoleId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10RoleIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10RoleId>>>
    export type PutApiV10RoleIdMutationBody = BodyType<RoleUpdate>
    export type PutApiV10RoleIdMutationError = ErrorType<void>

    /**
 * @summary Update role by ID
 */
export const usePutApiV10RoleId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10RoleId>>, TError,{id: string;data: BodyType<RoleUpdate>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10RoleId>>,
        TError,
        {id: string;data: BodyType<RoleUpdate>},
        TContext
      > => {

      const mutationOptions = getPutApiV10RoleIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a single role by its ID. Cannot delete system roles (admin).
 * @summary Delete role by ID
 */
export const deleteApiV10RoleId = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<void>(
      {url: `/api/v1.0/role/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV10RoleIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10RoleId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10RoleId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV10RoleId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV10RoleId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV10RoleId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV10RoleIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV10RoleId>>>
    
    export type DeleteApiV10RoleIdMutationError = ErrorType<void>

    /**
 * @summary Delete role by ID
 */
export const useDeleteApiV10RoleId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV10RoleId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV10RoleId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV10RoleIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieve a list of roles with pagination, filtering and sorting
 * @summary Get all roles
 */
export const getApiV10Role = (
    params?: GetApiV10RoleParams,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<ResponseGetAllData>(
      {url: `/api/v1.0/role`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV10RoleInfiniteQueryKey = (params?: GetApiV10RoleParams,) => {
    return [
    'infinite', `/api/v1.0/role`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetApiV10RoleQueryKey = (params?: GetApiV10RoleParams,) => {
    return [
    `/api/v1.0/role`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV10RoleInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Role>>>, TError = ErrorType<unknown>>(params?: GetApiV10RoleParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Role>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10RoleInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Role>>> = ({ signal }) => getApiV10Role(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Role>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10RoleInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Role>>>
export type GetApiV10RoleInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10RoleInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Role>>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10RoleParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Role>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Role>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Role>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10RoleInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Role>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10RoleParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Role>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Role>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Role>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10RoleInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Role>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10RoleParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Role>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all roles
 */

export function useGetApiV10RoleInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10Role>>>, TError = ErrorType<unknown>>(
 params?: GetApiV10RoleParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Role>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10RoleInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all roles
 */
export const prefetchGetApiV10RoleInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10Role>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10RoleParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10Role>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10RoleInfiniteQueryOptions(params,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10RoleQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10Role>>, TError = ErrorType<unknown>>(params?: GetApiV10RoleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Role>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10RoleQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10Role>>> = ({ signal }) => getApiV10Role(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10Role>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10RoleQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10Role>>>
export type GetApiV10RoleQueryError = ErrorType<unknown>


export function useGetApiV10Role<TData = Awaited<ReturnType<typeof getApiV10Role>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV10RoleParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Role>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Role>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Role>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Role<TData = Awaited<ReturnType<typeof getApiV10Role>>, TError = ErrorType<unknown>>(
 params?: GetApiV10RoleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Role>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10Role>>,
          TError,
          Awaited<ReturnType<typeof getApiV10Role>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10Role<TData = Awaited<ReturnType<typeof getApiV10Role>>, TError = ErrorType<unknown>>(
 params?: GetApiV10RoleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Role>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all roles
 */

export function useGetApiV10Role<TData = Awaited<ReturnType<typeof getApiV10Role>>, TError = ErrorType<unknown>>(
 params?: GetApiV10RoleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Role>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10RoleQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get all roles
 */
export const prefetchGetApiV10RoleQuery = async <TData = Awaited<ReturnType<typeof getApiV10Role>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, params?: GetApiV10RoleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10Role>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10RoleQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Create a new role with permissions
 * @summary Create a new role
 */
export const postApiV10Role = (
    postApiV10RoleBody: BodyType<PostApiV10RoleBody>,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<void>(
      {url: `/api/v1.0/role`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV10RoleBody, signal
    },
      options);
    }
  


export const getPostApiV10RoleMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Role>>, TError,{data: BodyType<PostApiV10RoleBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV10Role>>, TError,{data: BodyType<PostApiV10RoleBody>}, TContext> => {

const mutationKey = ['postApiV10Role'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV10Role>>, {data: BodyType<PostApiV10RoleBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV10Role(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV10RoleMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV10Role>>>
    export type PostApiV10RoleMutationBody = BodyType<PostApiV10RoleBody>
    export type PostApiV10RoleMutationError = ErrorType<unknown>

    /**
 * @summary Create a new role
 */
export const usePostApiV10Role = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV10Role>>, TError,{data: BodyType<PostApiV10RoleBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV10Role>>,
        TError,
        {data: BodyType<PostApiV10RoleBody>},
        TContext
      > => {

      const mutationOptions = getPostApiV10RoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Lấy danh sách permissions đã gán cho role (raw module/action)
 * @summary Get role permissions
 */
export const getApiV10RoleIdPermission = (
    id: string,
 options?: SecondParameter<typeof useCustomClient>,signal?: AbortSignal
) => {
      
      
      return useCustomClient<GetApiV10RoleIdPermission200>(
      {url: `/api/v1.0/role/${id}/permission`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV10RoleIdPermissionInfiniteQueryKey = (id?: string,) => {
    return [
    'infinite', `/api/v1.0/role/${id}/permission`
    ] as const;
    }

export const getGetApiV10RoleIdPermissionQueryKey = (id?: string,) => {
    return [
    `/api/v1.0/role/${id}/permission`
    ] as const;
    }

    
export const getGetApiV10RoleIdPermissionInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10RoleIdPermissionInfiniteQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>> = ({ signal }) => getApiV10RoleIdPermission(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10RoleIdPermissionInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>>
export type GetApiV10RoleIdPermissionInfiniteQueryError = ErrorType<unknown>


export function useGetApiV10RoleIdPermissionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10RoleIdPermission>>,
          TError,
          Awaited<ReturnType<typeof getApiV10RoleIdPermission>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10RoleIdPermissionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10RoleIdPermission>>,
          TError,
          Awaited<ReturnType<typeof getApiV10RoleIdPermission>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10RoleIdPermissionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get role permissions
 */

export function useGetApiV10RoleIdPermissionInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10RoleIdPermissionInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get role permissions
 */
export const prefetchGetApiV10RoleIdPermissionInfiniteQuery = async <TData = Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10RoleIdPermissionInfiniteQueryOptions(id,options)

  await queryClient.prefetchInfiniteQuery(queryOptions);

  return queryClient;
}



export const getGetApiV10RoleIdPermissionQueryOptions = <TData = Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV10RoleIdPermissionQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>> = ({ signal }) => getApiV10RoleIdPermission(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id),  retry: 3, retryDelay: 1000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV10RoleIdPermissionQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>>
export type GetApiV10RoleIdPermissionQueryError = ErrorType<unknown>


export function useGetApiV10RoleIdPermission<TData = Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10RoleIdPermission>>,
          TError,
          Awaited<ReturnType<typeof getApiV10RoleIdPermission>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10RoleIdPermission<TData = Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV10RoleIdPermission>>,
          TError,
          Awaited<ReturnType<typeof getApiV10RoleIdPermission>>
        > , 'initialData'
      >, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV10RoleIdPermission<TData = Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get role permissions
 */

export function useGetApiV10RoleIdPermission<TData = Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV10RoleIdPermissionQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary Get role permissions
 */
export const prefetchGetApiV10RoleIdPermissionQuery = async <TData = Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV10RoleIdPermission>>, TError, TData>>, request?: SecondParameter<typeof useCustomClient>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetApiV10RoleIdPermissionQueryOptions(id,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * Thay thế toàn bộ permissions của role. FE gửi full danh sách, BE tự thêm/xóa rows tương ứng.
 * @summary Replace role permissions
 */
export const putApiV10RoleIdPermission = (
    id: string,
    putApiV10RoleIdPermissionBody: BodyType<PutApiV10RoleIdPermissionBody>,
 options?: SecondParameter<typeof useCustomClient>,) => {
      
      
      return useCustomClient<void>(
      {url: `/api/v1.0/role/${id}/permission`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putApiV10RoleIdPermissionBody
    },
      options);
    }
  


export const getPutApiV10RoleIdPermissionMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10RoleIdPermission>>, TError,{id: string;data: BodyType<PutApiV10RoleIdPermissionBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV10RoleIdPermission>>, TError,{id: string;data: BodyType<PutApiV10RoleIdPermissionBody>}, TContext> => {

const mutationKey = ['putApiV10RoleIdPermission'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV10RoleIdPermission>>, {id: string;data: BodyType<PutApiV10RoleIdPermissionBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV10RoleIdPermission(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV10RoleIdPermissionMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV10RoleIdPermission>>>
    export type PutApiV10RoleIdPermissionMutationBody = BodyType<PutApiV10RoleIdPermissionBody>
    export type PutApiV10RoleIdPermissionMutationError = ErrorType<void>

    /**
 * @summary Replace role permissions
 */
export const usePutApiV10RoleIdPermission = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV10RoleIdPermission>>, TError,{id: string;data: BodyType<PutApiV10RoleIdPermissionBody>}, TContext>, request?: SecondParameter<typeof useCustomClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV10RoleIdPermission>>,
        TError,
        {id: string;data: BodyType<PutApiV10RoleIdPermissionBody>},
        TContext
      > => {

      const mutationOptions = getPutApiV10RoleIdPermissionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    