/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { BannerGetAllResponseResponseData } from './bannerGetAllResponseResponseData';
import type { BannerGetAllResponseViolations } from './bannerGetAllResponseViolations';

export interface BannerGetAllResponse {
  /** @nullable */
  message: string | null;
  /** @nullable */
  message_en: string | null;
  responseData: BannerGetAllResponseResponseData;
  status: string;
  timeStamp: string;
  /** @nullable */
  violations: BannerGetAllResponseViolations;
}
