/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { Banner } from './banner';
import type { BannerGetOneResponseViolations } from './bannerGetOneResponseViolations';

export interface BannerGetOneResponse {
  /** @nullable */
  message: string | null;
  /** @nullable */
  message_en: string | null;
  responseData: Banner;
  status: string;
  timeStamp: string;
  /** @nullable */
  violations: BannerGetOneResponseViolations;
}
