/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { BannerDeleteResponseResponseData } from './bannerDeleteResponseResponseData';
import type { BannerDeleteResponseViolations } from './bannerDeleteResponseViolations';

export interface BannerDeleteResponse {
  /** @nullable */
  message: string | null;
  /** @nullable */
  message_en: string | null;
  responseData: BannerDeleteResponseResponseData;
  status: string;
  timeStamp: string;
  /** @nullable */
  violations: BannerDeleteResponseViolations;
}
