/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryThumbnail } from './categoryThumbnail';

export interface Category {
  id?: string;
  name?: string;
  /** @nullable */
  name_en?: string | null;
  slug?: string;
  /** @nullable */
  url?: string | null;
  /**
   * @minimum 0
   * @nullable
   */
  sort_order?: number | null;
  /** @nullable */
  thumbnail_id?: string | null;
  /** @nullable */
  thumbnail?: CategoryThumbnail;
  created_at?: string;
  /** @nullable */
  created_by?: string | null;
  updated_at?: string;
  /** @nullable */
  updated_by?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  parent_id?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  description_en?: string | null;
}
