/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ContactCreateStatus } from './contactCreateStatus';

export interface ContactCreate {
  /** @maxLength 255 */
  fullname: string;
  /** @maxLength 255 */
  email: string;
  /** @maxLength 30 */
  phone?: string;
  /** @maxLength 255 */
  title: string;
  content: string;
  status: ContactCreateStatus;
}
