/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface ContactInfoUpdate {
  /** @nullable */
  key?: string | null;
  /** @nullable */
  value?: string | null;
  /** @nullable */
  display_order?: number | null;
  /** @nullable */
  is_active?: boolean | null;
}
