/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ContactStatus } from './contactStatus';

export interface Contact {
  id: string;
  /** @maxLength 255 */
  fullname: string;
  /** @maxLength 255 */
  email: string;
  /**
   * @maxLength 30
   * @nullable
   */
  phone?: string | null;
  /** @maxLength 255 */
  title: string;
  content: string;
  status: ContactStatus;
  created_at: string;
  updated_at: string;
  /** @nullable */
  created_by?: string | null;
  /** @nullable */
  updated_by?: string | null;
}
