/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ContactInfoDeleteResponseResponseData } from './contactInfoDeleteResponseResponseData';
import type { ContactInfoDeleteResponseViolations } from './contactInfoDeleteResponseViolations';

export interface ContactInfoDeleteResponse {
  /** @nullable */
  message: string | null;
  /** @nullable */
  message_en: string | null;
  responseData: ContactInfoDeleteResponseResponseData;
  status: string;
  timeStamp: string;
  /** @nullable */
  violations: ContactInfoDeleteResponseViolations;
}
