/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { DeleteHeaderConfigId200AllOf } from './deleteHeaderConfigId200AllOf';

export type DeleteHeaderConfigId200 = ApiResponse & DeleteHeaderConfigId200AllOf;
