/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { DeleteApiV10HeaderConfigId200AllOf } from './deleteApiV10HeaderConfigId200AllOf';

export type DeleteApiV10HeaderConfigId200 = ApiResponse & DeleteApiV10HeaderConfigId200AllOf;
