/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { GetHeaderConfigId200AllOf } from './getHeaderConfigId200AllOf';

export type GetHeaderConfigId200 = ApiResponse & GetHeaderConfigId200AllOf;
