/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface HeaderConfigMutate {
  name?: string;
  /** @nullable */
  name_en?: string | null;
  /** @nullable */
  url?: string | null;
  /**
   * @minimum 0
   * @nullable
   */
  sort_order?: number | null;
  /** @nullable */
  thumbnail_id?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  parent_id?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  description_en?: string | null;
}
