/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface JobCreate {
  title: string;
  /** @nullable */
  slug?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  department?: string | null;
  /** @nullable */
  location?: string | null;
  /** @nullable */
  employment_type?: string | null;
  /** @nullable */
  apply_url?: string | null;
  /** @nullable */
  apply_deadline?: string | null;
  /** @nullable */
  is_active?: boolean | null;
  /** @nullable */
  is_featured?: boolean | null;
  /** @nullable */
  published_at?: string | null;
}
