/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { JobDeleteResponseResponseData } from './jobDeleteResponseResponseData';
import type { JobDeleteResponseViolations } from './jobDeleteResponseViolations';

export interface JobDeleteResponse {
  /** @nullable */
  message: string | null;
  /** @nullable */
  message_en: string | null;
  responseData: JobDeleteResponseResponseData;
  status: string;
  timeStamp: string;
  /** @nullable */
  violations: JobDeleteResponseViolations;
}
