/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { JobGetAllResponseResponseData } from './jobGetAllResponseResponseData';
import type { JobGetAllResponseViolations } from './jobGetAllResponseViolations';

export interface JobGetAllResponse {
  /** @nullable */
  message: string | null;
  /** @nullable */
  message_en: string | null;
  responseData: JobGetAllResponseResponseData;
  status: string;
  timeStamp: string;
  /** @nullable */
  violations: JobGetAllResponseViolations;
}
