/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { Job } from './job';
import type { JobGetOneResponseViolations } from './jobGetOneResponseViolations';

export interface JobGetOneResponse {
  /** @nullable */
  message: string | null;
  /** @nullable */
  message_en: string | null;
  responseData: Job;
  status: string;
  timeStamp: string;
  /** @nullable */
  violations: JobGetOneResponseViolations;
}
