/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { JobCreate } from './jobCreate';
import type { JobUpdate } from './jobUpdate';

export type JobMutate = JobCreate | JobUpdate;
