/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { LeaderGetAllResponseResponseData } from './leaderGetAllResponseResponseData';
import type { LeaderGetAllResponseViolations } from './leaderGetAllResponseViolations';

export interface LeaderGetAllResponse {
  /** @nullable */
  message: string | null;
  /** @nullable */
  message_en: string | null;
  responseData: LeaderGetAllResponseResponseData;
  status: string;
  timeStamp: string;
  /** @nullable */
  violations: LeaderGetAllResponseViolations;
}
