/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface LeaderCreate {
  name: string;
  /** @nullable */
  slug?: string | null;
  /** @nullable */
  position?: string | null;
  /** @nullable */
  bio?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  avatar_id?: string | null;
  /** @nullable */
  linkedin_url?: string | null;
  /** @nullable */
  started_at?: string | null;
  /** @nullable */
  ended_at?: string | null;
  /** @nullable */
  display_order?: number | null;
  /** @nullable */
  is_active?: boolean | null;
}
