/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PageConfigCreateType } from './pageConfigCreateType';

export interface PageConfigCreate {
  name: string;
  /** @nullable */
  name_en?: string | null;
  path: string;
  /** @nullable */
  type?: PageConfigCreateType;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  description_en?: string | null;
  /** @nullable */
  is_active?: boolean | null;
}
