/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PageConfigUpdateType } from './pageConfigUpdateType';

export interface PageConfigUpdate {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  name_en?: string | null;
  /** @nullable */
  path?: string | null;
  /** @nullable */
  type?: PageConfigUpdateType;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  description_en?: string | null;
  /** @nullable */
  is_active?: boolean | null;
}
