/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export interface PageConfig {
  id: string;
  name: string;
  /** @nullable */
  name_en?: string | null;
  path: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  description_en?: string | null;
  is_active: boolean;
  created_at: string;
  /** @nullable */
  created_by?: string | null;
  updated_at: string;
  /** @nullable */
  updated_by?: string | null;
}
