/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PageConfigDeleteResponseResponseData } from './pageConfigDeleteResponseResponseData';
import type { PageConfigDeleteResponseViolations } from './pageConfigDeleteResponseViolations';

export interface PageConfigDeleteResponse {
  /** @nullable */
  message: string | null;
  /** @nullable */
  message_en: string | null;
  responseData: PageConfigDeleteResponseResponseData;
  status: string;
  timeStamp: string;
  /** @nullable */
  violations: PageConfigDeleteResponseViolations;
}
