/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PageConfigGetAllResponseResponseData } from './pageConfigGetAllResponseResponseData';
import type { PageConfigGetAllResponseViolations } from './pageConfigGetAllResponseViolations';

export interface PageConfigGetAllResponse {
  /** @nullable */
  message: string | null;
  /** @nullable */
  message_en: string | null;
  responseData: PageConfigGetAllResponseResponseData;
  status: string;
  timeStamp: string;
  /** @nullable */
  violations: PageConfigGetAllResponseViolations;
}
