/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type PageConfigCreateType = typeof PageConfigCreateType[keyof typeof PageConfigCreateType] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PageConfigCreateType = {
  designed: 'designed',
  content: 'content',
} as const;
