/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PageConfig } from './pageConfig';
import type { PageConfigGetOneResponseViolations } from './pageConfigGetOneResponseViolations';

export interface PageConfigGetOneResponse {
  /** @nullable */
  message: string | null;
  /** @nullable */
  message_en: string | null;
  responseData: PageConfig;
  status: string;
  timeStamp: string;
  /** @nullable */
  violations: PageConfigGetOneResponseViolations;
}
