/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */

export type PageConfigType = typeof PageConfigType[keyof typeof PageConfigType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PageConfigType = {
  designed: 'designed',
  content: 'content',
} as const;
