/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PartnerLogoSummary } from './partnerLogoSummary';

export interface Partner {
  id: string;
  name: string;
  slug: string;
  industry_ids: string[];
  /** @nullable */
  logo: PartnerLogoSummary;
  /** @nullable */
  rating: number | null;
  /** @nullable */
  address: string | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  website: string | null;
  created_at: string;
  /** @nullable */
  created_by?: string | null;
  updated_at: string;
  /** @nullable */
  updated_by?: string | null;
}
