/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PartnerGetAllResponseResponseData } from './partnerGetAllResponseResponseData';
import type { PartnerGetAllResponseViolations } from './partnerGetAllResponseViolations';

export interface PartnerGetAllResponse {
  /** @nullable */
  message: string | null;
  /** @nullable */
  message_en: string | null;
  responseData: PartnerGetAllResponseResponseData;
  status: string;
  timeStamp: string;
  /** @nullable */
  violations: PartnerGetAllResponseViolations;
}
