/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { Partner } from './partner';
import type { PartnerGetOneResponseViolations } from './partnerGetOneResponseViolations';

export interface PartnerGetOneResponse {
  /** @nullable */
  message: string | null;
  /** @nullable */
  message_en: string | null;
  responseData: Partner;
  status: string;
  timeStamp: string;
  /** @nullable */
  violations: PartnerGetOneResponseViolations;
}
