/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PartnerDeleteResponseResponseData } from './partnerDeleteResponseResponseData';
import type { PartnerDeleteResponseViolations } from './partnerDeleteResponseViolations';

export interface PartnerDeleteResponse {
  /** @nullable */
  message: string | null;
  /** @nullable */
  message_en: string | null;
  responseData: PartnerDeleteResponseResponseData;
  status: string;
  timeStamp: string;
  /** @nullable */
  violations: PartnerDeleteResponseViolations;
}
