/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from './apiResponse';
import type { PostApiV10HeaderConfig200AllOf } from './postApiV10HeaderConfig200AllOf';

export type PostApiV10HeaderConfig200 = ApiResponse & PostApiV10HeaderConfig200AllOf;
