/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PostReleaseMode } from './postReleaseMode';
import type { PageConfig } from './pageConfig';
import type { PostContentStructure } from './postContentStructure';

export interface Post {
  id: string;
  title: string;
  /** @nullable */
  thumbnail_id?: string | null;
  external_link: string;
  content: string;
  /** @nullable */
  release_at?: string | null;
  is_active: boolean;
  release_mode: PostReleaseMode;
  page_configs?: PageConfig[];
  created_at: string;
  /** @nullable */
  created_by?: string | null;
  updated_at: string;
  /** @nullable */
  updated_by?: string | null;
  /** @nullable */
  is_featured?: boolean | null;
  /**
   * @maxLength 20
   * @nullable
   */
  status?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  type?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  slug?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  is_hidden?: boolean | null;
  /** @nullable */
  published_at?: string | null;
  /** @nullable */
  expired_at?: string | null;
  /** @nullable */
  started_at?: string | null;
  /** @nullable */
  ended_at?: string | null;
  /** @nullable */
  registration_deadline?: string | null;
  /**
   * @maxLength 500
   * @nullable
   */
  location?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  participation_fee?: string | null;
  /** @nullable */
  content_structure?: PostContentStructure;
  /** @nullable */
  event_dates?: string[] | null;
}
