/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * VietProDev CMS Backend
 * Coded by Meu TEAM
 * OpenAPI spec version: 1.0.0
 */
import type { PostCreateReleaseMode } from './postCreateReleaseMode';
import type { PostCreateContentStructure } from './postCreateContentStructure';

export interface PostCreate {
  title: string;
  /** @nullable */
  thumbnail_id?: string | null;
  external_link?: string;
  content: string;
  /** @nullable */
  release_at?: string | null;
  is_active: boolean;
  release_mode: PostCreateReleaseMode;
  /** @nullable */
  page_config_id?: string | null;
  /** @nullable */
  page_config_ids?: string[] | null;
  /** @nullable */
  is_featured?: boolean | null;
  /**
   * @maxLength 20
   * @nullable
   */
  status?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  type?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  slug?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  is_hidden?: boolean | null;
  /** @nullable */
  published_at?: string | null;
  /** @nullable */
  expired_at?: string | null;
  /** @nullable */
  started_at?: string | null;
  /** @nullable */
  ended_at?: string | null;
  /** @nullable */
  registration_deadline?: string | null;
  /**
   * @maxLength 500
   * @nullable
   */
  location?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  participation_fee?: string | null;
  /** @nullable */
  content_structure?: PostCreateContentStructure;
  /** @nullable */
  event_dates?: string[] | null;
}
